# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# 🔗 https://vitejs.dev/guide/static-deploy#github-pages

name: GitHub Pages

on:
  push:
    branches:
      - feat/gh-pages # TODO: main

permissions:
  contents: read
  id-token: write
  pages: write

concurrency:
  group: 'gh-pages'
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm clean-install

      - run: npm run build

      - uses: actions/configure-pages@v5

      - uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - uses: actions/deploy-pages@v4
        id: deployment
